### ISSUE TITLE
How does the simulator work?

### ISSUE THREAD

**Issue by wildfang** [julianschill/klipper-led_effect#119]
I'm sorry for asking but I couldn't find any info in the doc nor does it work to try running app.py or simulator.py from the shell. How does it work?

Kind regards!

**Comment by julianschill** [comment]
Sorry for the lack of documentation. I am lazy in this regard. But checkout the video from West3d, where it is explained quite well: https://youtu.be/ZRuwBEOEA2c

**Comment by wildfang** [comment]
Thanks! I'm dumb, it didn't even cross my mind to just check the assets in the release tab lol.
