### ISSUE TITLE
Internal error caused by combination of effects

### ISSUE THREAD

**Issue by spikeygg** [julianschill/klipper-led_effect#120]
When I tried to use a set of effects by adding it to the configuration file and restarting klipper, Klipper wouldn't start citing: 
`Internal error during ready callback: 'colorArray' object has no attribute 'copy'`

This is what I added:
```[led_effect caselight_soaking]
autostart:              false
frame_rate:             24
leds:
    neopixel:caselight
layers:
    pattern    0.4   1.0      add   (0.0, 0.5, 1.0), (0.3, 0.5, 0.5), (0.0, 1.0, 0.0) 
```

I found that I could swap `pattern` with other styles to make it work. This pattern config worked great in the simulator.

**Comment by julianschill** [comment]
Thanks for reporting the isssue. Could you pleas also provide the definition of the neopixels (I need mainly the LED count) and a klippy.log?

**Comment by spikeygg** [comment]
Yes, sorry. I meant to include this. Definition of caselight:
```[neopixel caselight]
pin: PB6
chain_count: 68
color_order: GRBW
initial_RED: 0.0
initial_GREEN: 0.0
initial_BLUE: 0.0
initial_WHITE: 0.0
```

I think this klippy.log has the problem in it...
[klippy.log](https://github.com/julianschill/klipper-led_effect/files/10251963/klippy.log)

**Comment by julianschill** [comment]
It is fixed in the develop branch.
