### ISSUE TITLE
LED efect simulator GRB for BARf Voron led

### ISSUE THREAD

**Issue by locki-cz** [julianschill/klipper-led_effect#122]
Simulator generate colours in RGB but voron braf is 8 GRB leds ... it is possbile to make some switch for this?

**Comment by julianschill** [comment]
You define the color order in the neopixel section. If you have mixed them in one chain (GRB for Barf and GRBW for nozzle) define it like this:
```color_order: GRB, GRB, GRB, GRB, GRB, GRB, GRB, GRB, GRBW, GRBW```

**Comment by locki-cz** [comment]
I have it corrcetly in config, but it generate colours in simulator in RGB and I must rewrite it for every generated macro, I explain it probably wrong :)

**Comment by julianschill** [comment]
All effects are always in RGB and then get sent in the correct order to the LEDs following the configured color order.

**Comment by julianschill** [comment]
I will close this. There is nothing to be done here.
