### ISSUE TITLE
Update klipper ---> errors

### ISSUE THREAD

**Issue by MLeal91** [julianschill/klipper-led_effect#125]
After i make all upates , klipper, moonraker etc my led effects wont work and show error

![image](https://user-images.githubusercontent.com/96699409/211435723-434a5e15-90f3-4f92-b053-90f068a1e6f8.png)

**Comment by julianschill** [comment]
The plugin got deleted. To fix, re-run the installation script.

**Comment by MLeal91** [comment]
> The plugin got deleted. To fix, re-run the installation script.

now it works thankss man
