### ISSUE TITLE
Issue: Klipper MCU freezes during progress effect

### ISSUE THREAD

**Issue by EmanuelStassar** [julianschill/klipper-led_effect#127]
[Led effects config and printer config.zip](https://github.com/julianschill/klipper-led_effect/files/10467969/Led.effects.config.and.printer.config.zip)

As soon as printing progress starts, klipper crashes with an MCU error
![326328112_1628809064222658_5557927870006243618_n](https://user-images.githubusercontent.com/6449527/213747902-440b37bc-69c2-4447-8d14-1d873ffe1942.jpg)

A simpel progress effect works fine.

**Comment by julianschill** [comment]
Ok, I will look into it. If you could also provide a klippy.log, that would help a lot.

**Comment by EmanuelStassar** [comment]
[klippy-3.log](https://github.com/julianschill/klipper-led_effect/files/10470192/klippy-3.log)

Here is the Slippy log. And the version of led effects is: led_effect v0.0.9-0-g5d16b1c

I hope you can find the issue. BTW I managed to crash the simulator a few times while trying to get this effect right (on MAC OS on M1 MacBook Air)

**Comment by julianschill** [comment]
As the error says it has "Lost communication with the MCU" I don't think that is error is caused by the effect. Maybe the LEDs draw too much power and your board shuts down? Hard to say. The exact same effect works on my printer.

**Comment by EmanuelStassar** [comment]
That was it! Silly of me not to think about that. I reduced brightness of the white color and that solved the issue. I now have a nice green dot moving along a white ledstrip during printing. Thanks for looking into this and for the nice piece of coding!
