### ISSUE TITLE
led_effects is borked for use with dotstar led chains

### ISSUE THREAD

**Issue by TodWulff** [julianschill/klipper-led_effect#13]
As requested, this is your reminder... ;-)

"**Hagbard V2.1070**  Thank you. I think I know what the issue is. I made a change to read the color_order from the config, and apparently for dotstar there isnt such a  configuration. So for dotstar I have to assume the default color order. Should be a quick fix, once I'm home. Would you mind creating an issue on github as a reminder for me?"

Thread start: https://discord.com/channels/460117602945990666/635687829254701107/925020306156970024

**Comment by TodWulff** [comment]
Good day.  Would it be useful to provide you with a short strip of DotStart LEDs?  If so, PM me in Discord with your address and preferred carrier when shipping from the US and I will get some coming your way.  I understand your in the Czech Republic.

**Comment by julianschill** [comment]
Fixed with 2e84f6b
