### ISSUE TITLE
led_effect_erreur

### ISSUE THREAD

**Issue by Eloura74** [julianschill/klipper-led_effect#141]
![image](https://user-images.githubusercontent.com/95535946/229061095-e858bac6-307e-46ec-addf-3c92ba64763c.png)

![image](https://user-images.githubusercontent.com/95535946/229061330-1284249a-d662-44e7-b1a5-7865940ddfa7.png)

Hello, I have a real problem and I don't understand at all why.
since the klipper update, no effect works anymore, is anyone in this case?

**Comment by gdachs** [comment]
You just have not installed led_effects, or lost it on the update. [Install it again](https://github.com/julianschill/klipper-led_effect#installation)

**Comment by Eloura74** [comment]
![image](https://user-images.githubusercontent.com/95535946/229071653-fac622dc-1a2e-44ba-8e8f-4a2c33d1eb23.png)
However, it is installed correctly, how do I uninstall it?

**Comment by gdachs** [comment]
You didn't see the link?

**Comment by Eloura74** [comment]
it was actually very simple, thank you very much :)
