### ISSUE TITLE
Need Help for deactivate effects for certain LEDs 'STOP_LED_EFFECTS LEDS="neopixel:sample"'

### ISSUE THREAD

**Issue by Levitron86** [julianschill/klipper-led_effect#150]
Hey everyone,

i read from the STOP_LED_EFFECTS LEDS="neopixel::frame_leds" command to only deactivate effects for certain LEDs.

I would like to switch off only the Frame Leds without switching off the Stealthburner Led Effects. Setting the Frame Leds to RGB = 0 is not working, because rainbow effect blocks this command.

But if i set the Stop command for my frame LEDs it switch off all LEDs (Frame and SB_LEDS).

Is it necessary to call the neopixel:frame Leds for all my Effects? Because some i use only for the Stealthburner Leds, and some only for the frame. 

My Config is: 

[gcode_macro Frame_LEDs_OFF]
gcode:
    STOP_LED_EFFECTS LEDS="neopixel:frame_leds"
    _SET_FRAME_LEDS R=0 G=0 B=0

[led_effect rainbow]
autostart:                true
frame_rate:               24
leds:
     neopixel:frame_leds    
     neopixel:sb_leds
    
layers:
    gradient  0.5  1 add (0.2, 0.0, 0.0),(0.0, 0.2, 0.0),(0.0, 0.0, 0.2)

**Comment by julianschill** [comment]
It always deactivates the effect. You can't remove LEDs drom one effect. So easiest fix would be to split the effect into two effects.
