### ISSUE TITLE
Homing effect and quad gantry leveling

### ISSUE THREAD

**Issue by Spacedude** [julianschill/klipper-led_effect#152]
Unfortunately, the homing effect does not seem to work with QGL.

Sample code for a Voron Stealthburner setup:
```
[led_effect sb_nozzle_leveling]
autostart:              false
frame_rate:             24
endstops:               z
leds:
    neopixel:sb_leds (2,3)
layers:
    homing 3 0 top (1.0, 1.0, 1.0)
```

**Comment by julianschill** [comment]
For QGL use
`endstops: probe`

**Comment by Spacedude** [comment]
Ah, actually fully reading the documentation does indeed help it seems.
Sorry about that, closing this.
