### ISSUE TITLE
wxPthon seems unsupported for running simulator on windows

### ISSUE THREAD

**Issue by jwhite** [julianschill/klipper-led_effect#153]
WXPython seems to no support Python3.   Simulator seems to be difficult to impossible to run on Windows, even using python2 (dependencies don't seem to work with pip.)

Any thoughts going forward?

I make take a stab at implementing using kivy.  Does anyone have a screenshot of the GUI?

**Comment by julianschill** [comment]
I packaged it with Pyinstaller. You can find it under Releases. Just run that.

**Comment by julianschill** [comment]
I'm using poetry in Windows with python 3.10.8 by the way.
