### ISSUE TITLE
Control of multiple Pins not working

### ISSUE THREAD

**Issue by Boztech3D** [julianschill/klipper-led_effect#157]
I don't know how to word this so I will just post a sample. The first part works.

[neopixel sb_leds]
pin: PA8 #was PB0
#   The pin connected to the neopixel. This parameter must be provided.
chain_count: 3
#   The number of Neopixel chips that are "daisy chained" to the
#   provided pin. The default is 1 (which indicates only a single
#   Neopixel is connected to the pin).
color_order: GRB
#   Set the pixel order required by the LED hardware. Options are GRB,
#   RGB, GRBW, or RGBW. The default is GRB.
initial_RED: 1.0
initial_GREEN: 0.0
initial_BLUE: 1.0
#initial_WHITE: 0.0
#   Sets the initial LED color of the Neopixel. Each value should be
#   between 0.0 and 1.0. The WHITE option is only available on RGBW
#   LEDs. The default for each color is 0.#

This part does NOT work.
[neopixel top_bar]
pin: PC13
chain_count: 15
color_order: GRB
initial_RED: 1.0
initial_GREEN: 0.0
initial_BLUE: 1.0

I have added this as well.
[led_effect sb_logo_busy]
autostart:              false
frame_rate:             24
leds:
    neopixel:sb_leds (1)
    neopixel:top_bar
layers:
    breathing  3 1 top (1,0,0)
The Stealthburner lights seem to work. But the Top Bar only gets 3 out of 15 leds. Seems to mimic the Stealthburner lights. What am I doing wrong?

**Comment by julianschill** [comment]
This should work. First make sure the LEDs work with normal SET_LED commands. Stop all effects with STOP_LED_EFFECTS and run `SET_LED LED=top_bar RED=1`
Make sure they all light up red.
Also enclose your code with backticks ` or format them as code.

**Comment by Boztech3D** [comment]
Yes. When I stop led effects and issue red for the top bar it works fine.
Not sure what changed. But now I have no control over the nozzle LEDs. They
stay on blue. I don't understand back tics or what you meant.

**Comment by Boztech3D** [comment]
I thought I had solved the problem. I replaced the second nozzle LED because when I turn on nozzle LEDs it turns green. Here is the nozzle code I am using.
[led_effect set_nozzle_leds]
leds:
    neopixel:sb_leds (2,3)
   #neopixel:caselight
autostart:                          false
frame_rate:                         24
layers:
    static         0  0     top        (1.0,  1.0, 1.0)

So I am stump by why this is happening.

**Comment by julianschill** [comment]
Make sure you defined the correct color order.

**Comment by Boztech3D** [comment]
Ok. So I was about to try a whole new set of LEDs in the Stealthburner head. But then the idea just popped into my head. The stupid things are RGBW! All of my others are GRB. WOW! Well at least everything is working like it should. Hopefully someone else will read this and try RGBW. ;)
