### ISSUE TITLE
Install Error?

### ISSUE THREAD

**Issue by gedds1993** [julianschill/klipper-led_effect#166]
I tried to install this using putty for SSH, and I am getting an error that Moonraker isn't installed, which is true because I use Octoprint. Is Octoprint not supported?

![image](https://github.com/julianschill/klipper-led_effect/assets/82889685/6e468a31-6e59-448a-ae47-1b99ada34a8b)

**Comment by burntcoinpurse** [comment]
I use octoprint too but you can still install moonraker and use the led effects

```
git clone https://github.com/Arksine/moonraker.git
cd ~/moonraker/scripts
./install-moonraker.sh
git clone https://github.com/julianschill/klipper-led_effect.git
cd klipper-led_effect
./install-led_effect.sh
sudo reboot
```

**Comment by gedds1993** [comment]
> I use octoprint too but you can still install moonraker and use the led effects
> 
> ```
> git clone https://github.com/Arksine/moonraker.git
> cd ~/moonraker/scripts
> ./install-moonraker.sh
> git clone https://github.com/julianschill/klipper-led_effect.git
> cd klipper-led_effect
> ./install-led_effect.sh
> sudo reboot
> ```

I figured that’s what I’d have to do, glad to know it still works. Curious to know what in moonraker this module is dependent upon.

**Comment by gedds1993** [comment]
@julianschill much appreciated.

**Comment by davidreact** [comment]
I have multiple instances of klipper so the default paths for the folders and the klipper service didn't work. Not sure if it is possible to pass the variables. I had to change the default path on the script and the klipper and moonraker service.

How to check for the klipper/moonraker service name for the start and stop part: systemctl list-units --type=service

Ideally it should check for instances and ask which one do you want to install the led-effect to.

Attached modified script for reference
[install-led_effect.txt](https://github.com/julianschill/klipper-led_effect/files/13562755/install-led_effect.txt)
