### ISSUE TITLE
stealthburner file different from youtube video tutorial

### ISSUE THREAD

**Issue by stefi01** [julianschill/klipper-led_effect#177]
Trying to follow a tutorial video linked in their description to this repo the file he is editing has been updated, 
 where can I get the older file as his is easier to follow and this repo unfortunately is confusing [https://www.youtube.com/watch?v=SFKB2oBfFxA](url)

**Comment by julianschill** [comment]
The video was done before the examples existed I think. And the file showed there was created from scratch. But you can use the new files. Select the file that matches your setup, copy it, paste it in a file in your configuration and include that file on your printer.cfg. Adjust the neopixel pin and put the macros at the places where you need them.

I agree that the documentation is not very easy to read and I will rework it and write a step by step tutorial at some point.
