### ISSUE TITLE
Case lights switch off after booting up printer

### ISSUE THREAD

**Issue by norris108** [julianschill/klipper-led_effect#183]
Before I installed [klipper-led_effect](https://github.com/julianschill/klipper-led_effect), my case lights turned on and stayed on after booting up

Since installing [klipper-led_effect](https://github.com/julianschill/klipper-led_effect), my case lights turn on and a second later switch off after booting up

Is this by design?

I'm using [Klippain](https://github.com/Frix-x/klippain) and have this in `overrides.cfg`:

```
#-------------------------#
#      CASE LIGHTS        #
#-------------------------#

[neopixel caselight]
pin: CASELIGHT_NEOPIXEL
chain_count: 39
initial_RED: 1.0
initial_GREEN: 1.0
initial_BLUE: 1.0
```

**Comment by julianschill** [comment]
Make sure, you don't have any effects on autostart.

**Comment by julianschill** [comment]
Fixed by https://github.com/julianschill/klipper-led_effect/commit/71d8b30f23d7495fb1eb127e0a8fa1e530985ed2
