### ISSUE TITLE
Named led segments

### ISSUE THREAD

**Issue by therealzoomgod** [julianschill/klipper-led_effect#190]
Wanted your thoughts on this before I spend any time implementing and doing a pull request.   Rather then having to put in led numbers that will be used IE: (1, 2, 3...) or (7-20) I think it would be useful to have named led segments.  They can be stored and then retrieved in from a simple macro or possibly a config file.  I'm on day one with this add on, might already be a config file I haven't seen yet.

Anyway example of what I was thinking.

```
[gcode_macro led_effect_segments]
variable_right_side: "1-29"
variable_back: "30-70"
variable_left_side: "71-100"
gcode:
    {% set dummy=0 %}
```

Currently this would be my back segment of leds
  neopixel:chamber_leds (30-70)

That could become:
`  neopixel:chamber_leds (back)`
or you could even do:
`  neopixel:chamber_leds (left_side, right_side)`

Names are easier to remember.  If that is of interest I can start working on it.  Adding the parsing in parse_chain function should be easy.  Just where to store/retrieve the named segments would need decided.

Thanks

**Comment by julianschill** [comment]
Thanks for reaching out. I rather use a solution with virtually defined LEDs like implemented here: https://github.com/MapleLeafMakers/klipper-virtual_leds or in this pending Klipper PR: https://github.com/Klipper3d/klipper/pull/6446

This would give the maximum flexibility. You can already use it if you like. It should work with led-effect. You might have to define the virtual leds before your effects in the config.
