### ISSUE TITLE
Flickering, checked voltage

### ISSUE THREAD

**Issue by Caskia** [julianschill/klipper-led_effect#21]
Hi,
   Thank you for developing this cool project. I have cheked my strip voltage, it's stable at 5v and isolated it from other wires, but it seems to be flickering. Do you have any other ideas to fix it?

- led strip: SK6812
- led unit counts: 60
- mcu board: spider v1.1

**Comment by julianschill** [comment]
This seems to be a hardware issue. Make sure the LEDs work without effects first. Maybe you are drawing too much current.

I won't follow that here, as this is for issues with the effects software. Try to find help in the Klipper Discourse or Discord or contact me on discord. https://www.klipper3d.org/Contact.html

**Comment by Caskia** [comment]
If without effects, it works normal.
