### ISSUE TITLE
[BUG]  'MCU_adc' object has no attribute 'setup_minmax'

### ISSUE THREAD

**Issue by yet-another-average-joe** [julianschill/klipper-led_effect#211]
Klipper last update (v0.12.0-256-g6d700502) killed the "analog" feature.
A new ADC management was introduced with this commit. 

`self.mcu_adc.setup_minmax(ANALOG_SAMPLE_TIME, ANALOG_SAMPLE_COUNT)`
led_effect.py, line 366

doen't work anymore. setup_minmax() was replaced with setup_adc_sample() in Klipper.

Seems that renaming the function call in led_effect.py solves the problem, but now led_effect is "dirty" (of course)...

Replaced :

`self.mcu_adc.setup_minmax(ANALOG_SAMPLE_TIME, ANALOG_SAMPLE_COUNT)`

with

`self.mcu_adc.setup_adc_sample(ANALOG_SAMPLE_TIME, ANALOG_SAMPLE_COUNT)`

**Comment by julianschill** [comment]
Thanks for reporting. Will look into this.
