### ISSUE TITLE
Print progress  checking based on print percentage in klipper  through  Neopixel led lights  in LED_effect

### ISSUE THREAD

**Issue by Maxshapez** [julianschill/klipper-led_effect#212]
@julianschill Hi Julianschill, I am trying to use LED_efects created by you. however, in my scenario I would want to explicitly set progress for progress effect rather than polling the progress value from printer state object. I tried using M73 PXX command to override the progress number but this seems have only temporary effect and the LED are reset once the print progress value is re-polled from the printer status object. Kindly advice.

**Comment by julianschill** [comment]
LED effects gets the progress from the printer status. M73 sets the printer status. 
Check if you have M73 commands in your gcode file from the slicer that override your setting.

**Comment by Maxshapez** [comment]
we checked that there is nothing overriding the M73 bit when we are executing it after sometime the value is resetting itself

**Comment by julianschill** [comment]
Ok, but this is a Klipper issue then. LRD effects just reads the progress from the display_status object. Nothing else.

**Comment by Maxshapez** [comment]
Isn't it possible to parameterized the print progress and passed it as parameter

**Comment by julianschill** [comment]
It is, with M73. I'm not sure what resets it on your printer. As far as I know the print progress is ONLY set by M73. But I might be wrong.

**Comment by julianschill** [comment]
At least the Klipper documentation says that the print_progress variable contains the last value from M73. And that's what LED effects uses. https://www.klipper3d.org/Status_Reference.html#display_status
So check your slicer and macros for custom gcode containing M73.

**Comment by Maxshapez** [comment]
Iam not checking this during printing  i just trying it manually through mainsail when we try M73 PXX value it is working but it is resetting with in 5-10 secs 
 ( I am in Initial phase of testing LED_effect and finalizing  the color pattern in it)

**Comment by julianschill** [comment]
Looking at the Klipper code here https://github.com/Klipper3d/klipper/blob/master/klippy/extras/display_status.py

Klipper resets the progress after 5 seconds when there is no print running.
