### ISSUE TITLE
Error after update v0.0.13

### ISSUE THREAD

**Issue by 0815Pusher** [julianschill/klipper-led_effect#225]
Hello :)
I got this error after update:

**Internal error during connect: invalid syntax (led_effect.py, line 7)**
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

What can i do?

**Comment by julianschill** [comment]
Please provide a klippy.log. Also check if your led_effect.py is not modified.
To do that run this and post the output:
```cd ~/klipper-led_effect; git status```

**Comment by julianschill** [comment]
Ok, so somehow your led_effect.py is a html document. I would recommend uninstalling and reinstalling the plugin.

**Comment by 0815Pusher** [comment]
oh, yes i see
Thank you for your effort
