### ISSUE TITLE
[Feature Request] Turn off all effect

### ISSUE THREAD

**Issue by behold81** [julianschill/klipper-led_effect#30]
Maybe I have missed something obvious. but is there a way to turn off all effect so that the next effect if enabled can be the only one on. unless auto set lights. I want Macros to be able to be set at the start, mid and end of a print. I know I can right long code repeating all possible effects that might be on. but an all off would be good.

**Comment by julianschill** [comment]
Use the STOP_LED_EFFECTS command.
