### ISSUE TITLE
LED effects seem to cause issue with recent update

### ISSUE THREAD

**Issue by srothwel** [julianschill/klipper-led_effect#50]
Love the LED effects, but I have just updated Klipper, Moonraker and the Raspberry Pi OS via the links in Fluid and now I get an error _'internal error during ready callback: PrinterNeoPixel instance has no attribute 'chain_count'_  If I comment out the effects in the config file then everything back to normal but no LED Effects.  Declaring Neopixels in the config is still okay just not the effects.

**Comment by julianschill** [comment]
There were some changes in the LED code of klipper today. So LED effects might need some fix.

**Comment by julianschill** [comment]
Just to be sure: Have you defined chain_count in the neopixel configuration?

**Comment by meganssmith** [comment]
I got the same issue with mainsail today as well.  and yes all my neopixles had the chain_count set on them

**Comment by w35t13** [comment]
wish i saw this before i hit update haha

**Comment by julianschill** [comment]
As a workaround until I fix this, you can add the indices to the LED definition like this: `neopixel:my_leds (1-8)`
So e.g.:
```
[led_effect panel_idle]
autostart:              true
frame_rate:             24
leds:
    neopixel:panel_ring (1-8)
layers:
    breathing  10 1 top (.5,.5,1)
```

**Comment by srothwel** [comment]
Great, thanks for the workaround tip.  Look forward to some great exciting stuff.

⁣Sent from Blue ​

On 19 Apr 2022, 1:11 pm, at 1:11 pm, Julian Schill ***@***.***> wrote:
>As a workaround until I fix this, you can add the indices to the LED
>definition like this: `neopixel:my_leds (1-8)`
>So e.g.:
>```
>[led_effect panel_idle]
>autostart:              true
>frame_rate:             24
>leds:
>    neopixel:panel_ring (1-8)
>layers:
>    breathing  10 1 top (.5,.5,1)
>```
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/julianschill/klipper-led_effect/issues/50#issuecomment-1102569121
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by meganssmith** [comment]
thank you, that fixed my issues

**Comment by seb449** [comment]
Parfait cela contourne bien le pb, merci

**Comment by devolf92** [comment]
thanks! fix works

 ( start led # - end led #)

**Comment by srothwel** [comment]
Yes, chain_count is defined.  All the effects worked perfectly before I updated klipper, has produced the same error on all three printers!

⁣Sent from Blue ​

On 18 Apr 2022, 10:18 pm, at 10:18 pm, Julian Schill ***@***.***> wrote:
>Just to be sure: Have you defined chain_count in the neopixel
>configuration? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/julianschill/klipper-led_effect/issues/50#issuecomment-1101776949
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by julianschill** [comment]
This should be fixed already. Please update LED Effect to the newest version. If you still have problems, please provide the klippy.log.

**Comment by LazaroFilm** [comment]
Hi, I'm facing this error. adding (1-18) sends this error
```
Internal error during ready callback: invalid literal for int() with base 10: 'disco_leds(1'
```
