### ISSUE TITLE
Section 'led_effect panel_idle' is not a valid config section

### ISSUE THREAD

**Issue by DHinh** [julianschill/klipper-led_effect#59]
[neopixel panel_ring]			 
pin: PA9
chain_count: 20
[led_effect panel_idle]
autostart:              true
frame_rate:             24
leds:
    neopixel:panel_ring (1-20)
layers:
    breathing  10 1 top (.5,.5,1)
    
![Uploading 20220521112731.png…]()

**Comment by DHinh** [comment]
fluidd
v1.18.0

klipper
v0.10.0-408-g2c441b45-dirty -> v0.10.0-419

led_effect
v0.0.3-25-gba509d1

**Comment by julianschill** [comment]
Probably the plugin is not installed correctly. Try reinstalling.
