### ISSUE TITLE
Where to place "color_order_GRB: true" statement

### ISSUE THREAD

**Issue by Markus-1984** [julianschill/klipper-led_effect#6]
Hi,

first I want to say that you did great work.
Unfortuanly I don`t know where to put in the "color_order_GRB: true" statement.
I´ve tried in the config of my LED, in the config of my LED-Effect and in the config of the LED-Effect in the leds: section.
Please give me a hint.

Best regards
Markus

**Comment by julianschill** [comment]
Documentation is outdated in this regard. Put this in your neopixel section:

```color_order: GRB```

**Comment by Markus-1984** [comment]
That's what I've done in the config of the LED. If I set the color via Gcode, it's workin well. 
But in the effects, the palette is still in GRB instead of RGB. Is it correctly?

**Comment by julianschill** [comment]
I checked and it seems to be a bug. Thanks for pointing it out.

**Comment by julianschill** [comment]
@Markus-1984 I pushed a change that should fix this issue. Can you please test if it is working correctly now?

**Comment by Markus-1984** [comment]
Hi julian,

now it's working like it should. Thanks.
