### ISSUE TITLE
Leds flickering when printing

### ISSUE THREAD

**Issue by quicksilverstar** [julianschill/klipper-led_effect#62]
Hi, sorry to report this but I am have a problem with klipper-led-effect while printing, I have two channels 
One for a status led with 8 led and a toolhead led with 2

While printing I am finding that the blink is very random and flicker and the toolhead led are while and will just turn on and off random

I have the led on a decated controller running klipper firmware 

When I run the gcode when not printing it will work fine

I am running the latest klipper and fluidd software

**Comment by julianschill** [comment]
Try this: https://github.com/Drachenkaetzchen/Voron-Documentation/blob/neopixel/community/howto/drachenkatze/neopixel_guide.md#adding-a-100-ohm-resistor-to-combat-signal-integrity-issues

Other than that I suspect a broken wire somewhere. But also LED-Effect creates a lot of traffic. It could be, that it is too much. Try reducing the amount of LEDs and see if that helps.

**Comment by burntcoinpurse** [comment]
I have that issue when 2 or more effects are fighting for the same pixels. You got to make sure to clear out effects before starting a new ones, also if your using fade out, or delayed gcodes, you got to wait for them to finish.

**Comment by akhamar** [comment]
I've the same issue.

I'll try to be very explicit (I'm using a 100ohm resistor, I've actually tried multiple resistor).

1) So if I start by not using the effect and just ask the printer for RED (set_led led=toto red=1 green=0 blue=0 white=0). All the led will be RED.
2) I start a print. I stop a print.
3) I ask for effect, the LED actually show to incorrect color on effect BUT if I said all LED to 0 and ask a particular color ther LED show that color.
4) The only way to fix the plugin is to restart the MCU

This only occur if I start a print. If I don't start a print the effect are all good.

What I believe is going on : once the print is started, the table color of the plugin is getting corrupted and when we ask for a particular color this color is incorrectly rendered.

To add more : I'm using a chain of color_order: `GRBW,GRBW,GRB,GRB,GRB,GRB,GRB,GRB,GRB,GRB`

**Comment by julianschill** [comment]
My guess would be a problem with the signal integrity. What happens when you switch off the motors?

**Comment by akhamar** [comment]
Hi Julian !

As explained even with all motor disactivated the signal sent to LED will be corrupted (or wrong, I tend to wrong).
All regular signal not using your plugin always goes through perfectly with no error. You plugin work perfectly until a print is started. After the print is started your plugin won't be able to actually send the correct data to the LED while a simple SET_LED will.

As per the testing I have done, I'm pretty confident it's not the signals that is corrupted but the actual color that are sent with incorrect data (for each said color).

**Comment by akhamar** [comment]
You might have been right about the e-motor. What can I do to test and mitigate the issue ?

**Comment by akhamar** [comment]
I've bought a 2 pair twisted foiled cable for the motor cable, I'll keep you inform if that solved the issue.
As more ppl tend to use stealthburner and BARF led, they will get EM noise from motor most-likely.

**Comment by julianschill** [comment]
@burntcoinpurse try updating. In the newest version the effects should mix together.

@quicksilverstar Can this be closed?
