### ISSUE TITLE
[Help] Stepper function

### ISSUE THREAD

**Issue by husnainali09** [julianschill/klipper-led_effect#70]
I am trying to fire the led when klicky d2f hits the bed during qgl and mesh/g28 like a comet effect. Please advice how to achieve this using stepper function?

**Comment by husnainali09** [comment]
I'm not sure how that command works. This is my probe section in printer.cfg
![Screenshot_20220714-094115_Chrome](https://user-images.githubusercontent.com/56732835/178855232-95e85674-f2ee-491a-be2a-c19e172b2326.jpg)

**Comment by burntcoinpurse** [comment]
I'll write it out for you in a few hours when I'm home. Work....ya know.

**Comment by burntcoinpurse** [comment]
Can you post you neopixel stuff too? It'll make it easier.

**Comment by husnainali09** [comment]
`[neopixel sb_leds]
pin: sht36:PB15
chain_count: 3
color_order: GRBW
initial_RED: 1.0
initial_GREEN: 0.0
initial_BLUE: 1.0
initial_WHITE: 0.0`

**Comment by husnainali09** [comment]
[gcode_macro PRINT_START]
variable_parameter_PRINT_MIN : 0,0
variable_parameter_PRINT_MAX : 0,0
gcode:
    # Parameters
    {% set bedtemp = params.BED|int %}
    {% set hotendtemp = params.HOTEND|int %}
    {% set Chamber = params.CHAMBER|default(0)|int %}

    CLEAR_PAUSE
    SAVE_GCODE_STATE NAME=STATE_PRINT_START
    SET_LED_EFFECT EFFECT=bed_effects
    G4 P500
    M190 S{bedtemp}                ; set and wait for bed temp
    G28
    HEATSOAK T={bedtemp} MOVE=1
    TEMPERATURE_WAIT SENSOR="temperature_sensor Chamber" MINIMUM={Chamber}
    SET_LED_EFFECT EFFECT=bed_effects STOP=1
    STATUS_READY
	M104 S175                      ; set and wait for hotend temp
    BedsFansSlow
	M107						   ; Fan off
	BED_MESH_CLEAR				   ; Clear Bed Mesh
    STATUS_HOMING
	G28 X Y
	ATTACH_PROBE_LOCK
    STATUS_READY
    STATUS_CALIBRATING_Z
    G28 Z                            ; home all axes
    STATUS_READY
    STATUS_LEVELING
    QUAD_GANTRY_LEVEL
	G28 Z
    STATUS_READY
	G90 													 											; absolute positioning
	G0 Z20 F3000
    STATUS_MESHING
    BED_MESH_CALIBRATE PRINT_MIN={params.PRINT_MIN} PRINT_MAX={params.PRINT_MAX}                       ; Print area bed mesh calibrate
	DOCK_PROBE_UNLOCK
    STATUS_READY
    STATUS_HEATING
	M109 S{hotendtemp}             ; set and wait for hotend temp
    STATUS_READY
    #STATUS_CLEANING
	# scrub_nozzle
    STATUS_PRINTING
	G92 E0                              																; reset Extruder
	G1 X0 Y20 Z0.3 F19500.0           																	; move to start position
	G1 X0 Y200.0 Z0.3 F1500.0 E15     																	; draw the first line
	G92 E0                              																; reset Extruder
	G1 Z2.0 F3000  
    #SET_FILAMENT_SENSOR SENSOR=filament_sensor ENABLE=1
    
    RESTORE_GCODE_STATE NAME=STATE_PRINT_START

**Comment by husnainali09** [comment]
Thank you for looking into this !

**Comment by burntcoinpurse** [comment]
You got it working?

**Comment by burntcoinpurse** [comment]
You're going to need to set up a display_template for the macro.

**Comment by husnainali09** [comment]
> You're going to need to set up a display_template for the macro. Give each effect its own display_template. Then use the macro to run the template.

[led_effect bed_effects]
leds:
    neopixel:sb_leds
autostart:                          false
frame_rate:                         24
heater:                             heater_bed
layers:
    heaterfire  50 0 add    (1,1,0),(1,0,0)
    static  0  0 top    (1,0,0)

[gcode_macro LED_White]
gcode:
    SET_LED LED=case_leds RED=1.0 GREEN=1.0 BLUE=0.5

[led_effect critical_error]
leds:
    neopixel:sb_leds
layers:
    strobe         1  1.5   add        (1.0,  1.0, 1.0)
    breathing      2  0     difference (0.95, 0.0, 0.0)
    static         1  0     top        (1.0,  0.0, 0.0)
autostart:                             false
frame_rate:                            24
run_on_error:                          true

**Comment by husnainali09** [comment]
This is what i am using for bed effects etc but its the klicky trigger effect that i am chasing

**Comment by burntcoinpurse** [comment]
activate_gcode:
[gcode_macro KLICKY]
gcode:
    SET_LED_EFFECT EFFECT="your effect"
deactivate_gcode:
[gcode_macro KLICKY]
gcode:
    SET_LED_EFFECT EFFECT="your effect" STOP=1

add this to [probe] in printer.cfg to start an effect as soon as the probe deploys, and the second to cancel it when it retracts

or 

deactivate_gcode:
[gcode_macro KLICKY_BLINK]
gcode:
  SET_LED LED=sb_leds RED=1 GREEN=0 BLUE=0 WHITE=0 
  G4 P2000
  SET_LED LED=sb_leds  RED=0 GREEN=0 BLUE=0 WHITE=0 

you can try this one which should flash red for 2 seconds after the probe triggers. 
Let me know how it works. I'm going to be installing my chamber heater lol

**Comment by MLeal91** [comment]
> activate_gcode: [gcode_macro KLICKY] gcode: SET_LED_EFFECT EFFECT="your effect" deactivate_gcode: [gcode_macro KLICKY_OFF] gcode: SET_LED_EFFECT EFFECT="your effect" STOP=1
> 
> add this to [probe] in printer.cfg to start an effect as soon as the probe deploys, and the second to cancel it when it retracts
> 
> or
> 
> deactivate_gcode: [gcode_macro KLICKY_BLINK] gcode: SET_LED LED=sb_leds RED=1 GREEN=0 BLUE=0 WHITE=0 FADETIME=0.5 G4 P500 SET_LED LED=sb_leds RED=0 GREEN=0 BLUE=0 WHITE=0 FADETIME=0.5
> 
> you can try this one which should flash red for 2 seconds after the probe triggers. Let me know how it works. I'm going to be installing my chamber heater lol

dont work for me.... i want make some leed effect when switch hit he plate and this dont work. will try the "stepper" effect dont work either

someone can help?

**Comment by julianschill** [comment]
I am currently working on such an effect. So stay tuned. Will be releases soon.

**Comment by MLeal91** [comment]
> I am currently working on such an effect. So stay tuned. Will be released soon.

I will be watching the channel and thank you

**Comment by julianschill** [comment]
Solved by new homing effect. Multiply it with a white palette and the underlying effect will show.
