### ISSUE TITLE
update broken

### ISSUE THREAD

**Issue by jangrewe** [julianschill/klipper-led_effect#71]
Not sure if this is new or never worked, but the update config for moonraker needs `primary_branch: master` added for the update to work - at least on my setup.

**Comment by julianschill** [comment]
The default on moonraker is "master". So I don't think it needs to be defined.

**Comment by julianschill** [comment]
The default on moonraker is "master". So I don't think it needs to be defined.

**Comment by julianschill** [comment]
The default on moonraker is "master". So I don't think it needs to be defined.
