### ISSUE TITLE
Calculation of stepper position (as %) is incorrect for non-zero min axis

### ISSUE THREAD

**Issue by guru-florida** [julianschill/klipper-led_effect#76]
This percent calculation seems incorrect on [line 152](https://github.com/julianschill/klipper-led_effect/blob/f12dcdc21d10dafa0e8788b9869d0c4b09c0c308/src/led_effect.py#L152):
```python
 self.stepperPositions[i] = int(
                    (pos[i] / (self.kin.axes_max[i] - self.kin.axes_min[i])
                        * 100)- 1)
```

The pos[i] range would be between min < max, but the denominator part of the division is the magnitude of {min,max}...therefor `pos[i]` should be `(pos[i] - self.kin.axes_min[i])` so that the numerator becomes a value between 0 and the magnitude of {min,max}. 

So I believe the code should be:
```python
 self.stepperPositions[i] = int(
                    ((pos[i] - self.kin.axes_min[i]) / (self.kin.axes_max[i] - self.kin.axes_min[i])
                        * 100)- 1)
```

That would get you a percentage between 0 and 1...except that trailing -1 is weird...so perhaps a final value between -1 and 99.

**Comment by julianschill** [comment]
I think it has to be `(pos[i] + self.kin.axes_min[i])`.

**Comment by guru-florida** [comment]
If you want to have a percentage between min and max, then I would say it needs to subtract the axis_min...you also subtract the axis_min in the denominator as well.
