### ISSUE TITLE
How do I start with one effect then after a time, automatically switch to another?

### ISSUE THREAD

**Issue by Gliptopolis** [julianschill/klipper-led_effect#77]
I see the FADETIME option but it seems that has to be tied to a macro? I'd like the machine to boot up with one effect then after a couple seconds switch to another one. Imagine a comet effect for a couple seconds then switching to a static color. Can I use the FADETIME as part of the effect description and make it autostart: true ?

**Comment by gdachs** [comment]
IMHO this is not an issue, because you can do that without any change to klipper-led_effect. Just use https://www.klipper3d.org/Config_Reference.html#idle_timeout

**Comment by burntcoinpurse** [comment]
You can set a gcode command in octoprint to initiate on the serial connection. If that helps.

**Comment by Gliptopolis** [comment]
> You can set a gcode command in octoprint to initiate on the serial connection. If that helps.

I'm using Mainsail so not sure if this carries over or not? I can't find any references to this in klipper docs

**Comment by julianschill** [comment]
Use delayed gcode for that. https://www.klipper3d.org/Config_Reference.html?#delayed_gcode

**Comment by Gliptopolis** [comment]
I have a delayed gcode in my printer.cfg but it doesn't do anything as far as I can tell.

**Comment by julianschill** [comment]
Set autostart to true for the first effect and start the second effect with the delayed_gcode like this:

`[delayed_gcode startup_effect]
initial_duration: 3
gcode:
  SET_LED_EFFECT EFFECT=first_effect STOP=1
  SET_LED_EFFECT EFFECT=second_effect`
