### ISSUE TITLE
Gradient effect cycling too fast

### ISSUE THREAD

**Issue by CoalBob** [julianschill/klipper-led_effect#78]
setup: 8LEDs with a single layer of gradient effect, speed set to '1', with 3 color as palette. And it turns out almosts flickering through the colors. Speed set to like '0.1' will results as low frame rate. Any fixes? Thank you.

**Comment by julianschill** [comment]
This is a known issue and will be fixed by https://github.com/julianschill/klipper-led_effect/issues/42
