### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by dagov42** [julianschill/klipper-led_effect#82]
After update klipper to v0.10.0-571-g97a5b39a led-effect dont work. 
Log is: 

> Config error
> Traceback (most recent call last):
>   File "/home/klipper/klipper/klippy/klippy.py", line 175, in _connect
>     self._read_config()
>   File "/home/klipper/klipper/klippy/klippy.py", line 145, in _read_config
>     pconfig.check_unused_options(config)
>   File "/home/klipper/klipper/klippy/configfile.py", line 295, in check_unused_options
>     raise error("Section '%s' is not a valid config section"
> configparser.Error: Section 'led_effect preheat' is not a valid config section
> webhooks client 547694102464: New connection
> webhooks client 547694102464: Client info {'program': 'Moonraker', 'version': 'v0.7.1-660-g5d856b9'}

**Comment by julianschill** [comment]
Please try reinstalling led_effect.

**Comment by julianschill** [comment]
@dagov42 Is it working for you now? Can this be closed?

**Comment by dagov42** [comment]
Yes, you can do it. It was klipper updating bug.
